oxen-io/oxen-storage-server

storage/vendor/sqlite/CMakeLists.txt
When integrating the storage server into lokid, I got errors due to the optimisation flag `-Ofast`, that is set by the lokid cmakelist, not being supported by SQLite.
This PR make it only use the default hardening flags.
(Note: the cmake scope does not bubble up after outside of add_subdirectory, so this won't affect anything upstream)
=> Clear CMake flags from upstream scope

httpserver/http_connection.hpp, pow/include/pow.hpp, pow/src/pow.cpp
checkPoW function now stores the message hash in string argument reference
This hash is now stored in the db as unique identifier for each message
=> Storing message hash in database

contrib/Findsodium.cmake, crypto/CMakeLists.txt
Somehow some files slipped through my fingers.
`contrib/Findsodium.cmake` is copy/pasta from the official cmake file for libsodium.
=> Missing files for channel encryption

httpserver/CMakeLists.txt, httpserver/http_connection.hpp, httpserver/main.cpp
Allows to specify `--log-level trace/debug/info/warning/error/fatal` optionally (default: `info`)
Ran `clang-format` so there are some noisy styling changes, sorry.
Please review the log level used for each message and if I could add more messages.
=> Add --log-level flag and use boost trivial logger

httpserver/service_node.cpp, httpserver/swarm.cpp
- additionally we no longer assume that all_swarms is sorted
=> account for sentinel value for swarm id in pk mapping

httpserver/http_connection.cpp, httpserver/http_connection.h, httpserver/main.cpp, httpserver/service_node.cpp, httpserver/service_node.h, httpserver/swarm.cpp, httpserver/swarm.h
Added 421 response for client requests to wrong swarm along with the correct swarm information
Added command line arg to output boost logs to file for easier log management with the messenger testnet (this may be made redundant by the launcher)
Fixed an ifdef mistake I put in before
=> Wrong swarm response

crypto/src/lokinet_identity.cpp, httpserver/serialization.cpp
Basically, we should serialize the size prefix in the same endianness as in memory (little endian, i.e. the LSB is at a lower memory address and is read first).
That way there's no need to convert little to big during serialization, then back to little during deserialization. You can just reinterpret as is.
Also, applied some `const` here and there, and replaced magic numbers with their `sizeof` meaning.
=> Simplify serialisation

httpserver/http_connection.cpp
Fixes what's been broken for integration tests by #33
=> correctly read swarm update response in integration tests

httpserver/swarm.cpp, httpserver/swarm.h
Started with a very small fix PR about adding an early `break` in a loop that was finding an index.
Ended up changing a bunch of loops to use STL.
Also some best practice nits.
Note: could not run any tests or executable to check if this PR introduces undesired behaviour.
=> Use STL instead of loops for snode/swarm find operations

httpserver/service_node.cpp, httpserver/swarm.cpp, httpserver/swarm.h
This way the numerous calls to `other_nodes()` are not doing anything except return the cached values :)
=> Exclude own snode from swarm peers

httpserver/common.h, httpserver/http_connection.cpp, httpserver/http_connection.h, httpserver/serialization.cpp, httpserver/service_node.cpp, httpserver/service_node.h
Adds basic infrastructure for recording snode errors (starting with snode being unreachable). The recording information is unused at the moment.
=> basic error recording in snode communication

httpserver/serialization.cpp, httpserver/serialization.h
=> Use boost::endian to ensure serialised data is little endian

CmakeLists.txt, Makefile, README.md, httpserver/CMakeLists.txt, pow/CMakeLists.txt, storage/CMakeLists.txt, unit_test/CMakeLists.txt
This allows running `make` from the repo root.
Also, the subdirectory are now "shared", e.g. the unit tests will link against the same libraries as the httpserver, instead of rebuilding them in a new subdirectory.
This PR will eventually simplify CD/CI commands.
=> Simplify build flow with a top-level makefile and cmakelist

httpserver/swarm.cpp
The messenger nodes would complain about a new service node (themselves) joining their swarm every time they polled lokid
=> Make sure we don't think we are a new SN

httpserver/swarm.cpp
Shouldn't be a problem for real swarms, but comes up in tests when I manually create swarms with one snode each.
=> fix entering the same swarm multiple times in case we are the only node

httpserver/CMakeLists.txt
for people still needing it, I think they can use this form:
`BOOST_LOG_DYN_LINK=ON make`
=> Remove BOOST_LOG_DYN_LINK flag

pow/src/pow.cpp, storage/src/Database.cpp, unit_test/storage.cpp, utils/src/utils.cpp
Update calculations to expect ttl to be in milliseconds instead of seconds, require non-zero ttl because might make PoW target nonsense
=> Millisecond ttl

storage/include/Database.hpp, storage/src/Database.cpp, unit_test/storage.cpp
Added a new `bulk_store` entrypoint to the storage api.
Also added a new argument in the `store` function, to use the `INSERT OR IGNORE` sql statement when set to true. This will ensure the bulk transaction doesn't fail when the UNIQUE constraint is violated by inserting entries already present.
=> Bulk store using sqlite transactions

unit_test/storage.cpp
Linux builds on travis doesn't like mixing std::thread/std::chrono within the boost unit test, go figure.
This reverts commit 9dc29a01b07b056347e270fac1119c42005730b3.
=> Revert "Use std:: instead of boost:: for chrono and thread"

httpserver/http_connection.cpp, httpserver/http_connection.h, httpserver/service_node.cpp, httpserver/service_node.h
- effectively this enables "resending" functionality for batches of messages (and simplifies code)
- the use of shared_ptr for requests is also supposed to reduce memory usage in batched transfers
=> combine code for single messages and batches

storage/src/Database.cpp
Clang static analyzer didn't like that we used a pointer without checking for nullity first.
=> Proper use of sqlite error message

httpserver/http_connection.cpp
Note that this is a breaking change: it depends on lokid #577 (which eliminated the need to parse the json response twice, which was silly).
=> use non-as-json rpc call for swarms

CMakeLists.txt, Makefile, httpserver/CMakeLists.txt
`make integration-test` builds the storage server with the correct flags for integration tests.
(could not confirm with integration tests because of `Bad lokid rpc response: invalid json` but the build seems to have the correct flags)
=> make shortcut for integration tests

httpserver/http_connection.cpp, httpserver/service_node.cpp, utils/include/utils.hpp, utils/src/utils.cpp
Add `verify_message`, which checks ttl, timestamp, PoW and hash, in `process_push` and `process_push_batch`.
For batch, we remove the messages that are invalid but keep the ones valid.
=> Verify proof of work for relayed messages

CMakeLists.txt, crypto/include/signature.h, crypto/src/signature.cpp, httpserver/http_connection.cpp, httpserver/service_node.cpp, httpserver/service_node.h, unit_test/signature.cpp
Integration tests were failing with signature due to the list of peers being empty, hence the signature was rejected. The solution for now is just to skip that check for integration test build.
Also, refactor the data relaying code since it was mostly redundant between `boostrap_peers` and `boostrap_swarms`
=> Refactor relaying code and fix signature for integration tests

unit_test/storage.cpp
Performance test (bulk vs single insert) is printing lots and lots of
`[error]   sqlite reset error: 19`
due to the second case (single insert) pushing the same messages to the database created by the first case (bulk).
This PR simply ensures the databases are deleted before each case.
Surprisingly, the single push performance got a lot worse (~7 seconds compare to 25ms for bulk!!) probably due to repeated disk memory allocation? It probably used to be an order of magnitude lower when the constraint failed, thanks to not having to actually allocate memory.
=> Clear database before performance testing

httpserver/service_node.cpp, httpserver/service_node.h, storage/include/Database.hpp, storage/src/Database.cpp, unit_test/storage.cpp
Implements #123 
Note that SQLITE states 
` If the LIMIT expression evaluates to a negative value, then there is no upper bound on the number of rows returned` so we can use `-1` to specify we don't want to limit the results.
=> Limit client retrieve request to 10 messages at a time

httpserver/http_connection.cpp
This PR uses the `acceptor::async_accept` overload that provides the socket as argument of the lambda. The acceptor can already generate the socket for us, per connection. This is safer than moving the socket into the `connection_t` constructor then passing it (in an undefined/reset state?) to `accept_connection` to close the loop.
=> Use safer acceptor::async_accept overload

Makefile, httpserver/CMakeLists.txt, httpserver/http_connection.cpp, httpserver/http_connection.h, httpserver/main.cpp, httpserver/rate_limiter.cpp, httpserver/rate_limiter.h, httpserver/service_node.cpp, httpserver/service_node.h, unit_test/CMakeLists.txt, unit_test/rate_limiter.cpp, unit_test/storage.cpp
Use  token-bucket algorithm to implement rate limiting.
Returns HTTP code `too_many_requests`.
Values for `BUCKET_SIZE` and `TOKEN_RATE` are still to be fine tuned, currently set to allow max 5 connections per seconds on average.
(PR is slightly tainted by clang format)
See #98
=> Token Bucket rate limiting for snode-to-snode requests

httpserver/rate_limiter.cpp
Seems to be dependent on the c++ version used.
=> fix static member not defined in cpp

httpserver/http_connection.cpp, httpserver/http_connection.h, httpserver/main.cpp, httpserver/service_node.cpp, httpserver/service_node.h, utils/include/utils.hpp, vendors/loki/crypto-ops/hash-ops.c
- uses the same tester/testee pair as in storage testing
- the main difference with storage testing is that the tester has to perform blockchain testing routine asynchronously to compute the answer before sending a test request to testee (storage testing uses a fast synchronous computation in its place).
=> perform blockchain testing alongside storage testing

httpserver/common.h, httpserver/http_connection.cpp, httpserver/http_connection.h, httpserver/service_node.h
Save the IP and port which is now being sent from lokid
Send the IP and port to clients as well
NOTE: Will need to update the integration tests to work with the change from "port" to "storage_port"
https://github.com/msgmaxim/swarm_migration_testing/pull/2
=> Send ports

.vscode/c_cpp_properties.json, crypto/include/lokid_key.h, crypto/include/signature.h, httpserver/CMakeLists.txt, httpserver/http_connection.cpp, httpserver/main.cpp, httpserver/rate_limiter.cpp, httpserver/service_node.cpp, httpserver/service_node.h, pow/include/pow.hpp, pow/src/pow.cpp, unit_test/pow.cpp
Every 10 mins the snodes will query the sentinel dns text record to get their PoW difficulty (previously NONCE_TRIALS)
Snodes will now send the difficulty with every successful request to allow clients to lower their difficulty if needed
Snodes will now send the difficulty with a 402: payment_required response when the clients provide invalid PoW to allow them to raise their difficulty if needed
Also added a lil bit to vscode settings to make my vscode experience a lil nicer and I think there was a couple straggler clang format changes that weren't caused by my changes
closes #138
=> Adjustable PoW difficulty

httpserver/http_connection.cpp, httpserver/https_client.cpp
tls 1.3 is only available in a newer version of boost, so I sticked to the newest protocol that boost 1.66 supports...
=> Change ssl context to TLS

httpserver/http_connection.cpp, httpserver/service_node.cpp, httpserver/service_node.h, pow/CMakeLists.txt, pow/include/pow.hpp, pow/src/pow.cpp, unit_test/pow.cpp
Bit of a chaotic PR
PoW difficulty is now loaded from the DNS record in the format `{"timestamp":difficulty,"timestamp":difficulty}`
This should represent at least the last 4 days of difficulties
When verifying a client message, we always use the most recent difficulty
When verifying messages pushed by other snodes we use the smallest of either: the most recent difficulty in the past OR any difficulty 15 minutes before or after the message timestamp
This is to allow for messages that were accepted by snodes that hadn't updated their difficulty yet
The difficulty timer is handled by the worker thread and then posts the result to the main thread to update the ServiceNode value
Don't know how I feel about passing in length 1 vector for the client verification, just wanted to get it working …
=> Difficulty history

httpserver/service_node.cpp
This could potentially break the integration tests?
make_sn_request was still trying to use snode address instead of ip
=> Clearnet test requests

httpserver/http_connection.cpp, httpserver/service_node.cpp, httpserver/service_node.h
Still attach the pubkey to test requests if signatures are disabled. Still check for header on the other side if signatures are disabled
=> Check header

httpserver/CMakeLists.txt, httpserver/common.h, httpserver/http_connection.cpp, httpserver/http_connection.h, httpserver/https_client.cpp, httpserver/server_certificates.h, httpserver/service_node.cpp, httpserver/service_node.h, httpserver/stats.cpp, httpserver/stats.h
Exposes GET `/v1/swarms/get_stats`.
Sample response:
```
{
"client_store_requests": 10,
"peers": {
"hizcwd3jhqe4wi55j1pf6ruz4eb4mesttxrwtcbim4j84qqdh5dy.snode": {
"blockchain_tests": [],
"pushes_failed": 0,
"requests_failed": 0,
"storage_tests": [
{
"success": true,
"timestamp": 1560750454
}
]
}
},
"reset_time": 1560750445,
"client_retrieve_requests": 0
}
```
`reset_time` - time since last restart (UNIX time, seconds)
`client_store_requests` - number of times got a store request directly from a client
`client_retrieve_requests` - number of times got a retrieve request directly from a client
`peers` - per peer stats:
`blockchain_tests` - a list of blockchain test results from a peer, a single entry is comprised of a boolean `success` to indicate the outcome of the test and `timestamp` in …
=> Provide RPC endpoint for retrieving peer test results and other stats

httpserver/common.h, httpserver/http_connection.cpp, httpserver/service_node.cpp
- eliminates the need to strip the `.snode` part from the address on every request for signing
- makes the API a bit more clear
=> Store both pubkey and snode address per snode

httpserver/http_connection.cpp, httpserver/http_connection.h, httpserver/serialization.cpp, httpserver/service_node.cpp
Makes all "swarms" requests share the same code path that verifies service node signatures before being passed to request-specific handlers. This code will need much more refactoring (like parsing the "target" value into components), but this is a first step.
=> small refactor: use common function for sn-sn calls

.travis.yml, unit_test/rate_limiter.cpp
Changing values to 600/300 broke the tests, as it requires a more fine-grained time scale.
Also reduced the unit test log level, preventing gazillion lines to be printed out.
=> Fix unit tests for rate limiter

httpserver/service_node.cpp, httpserver/service_node.h, httpserver/swarm.h
We don't want to process blocks (testing, pushing messages etc) that we receive while lokid is still syncing
=> Use the new target_height field to determine if lokid is still syncing

.travis.yml, Makefile, httpserver/CMakeLists.txt, install-deps-linux.sh, vendors/sqlite/CMakeLists.txt
EDIT: Finally fixed it!
The real issue was that travis had cached an empty install of openssl (maybe the first time it ran the install script failed). So instead of checking for the `deps/openssl` folder we should check for an actual file e.g. `deps/openssl/include/ssl.h` to determine if openssl is there.
=> Fix travis

httpserver/main.cpp
This allows specifying any of the `--whatever xyz` parameters via a
`whatever=xyz` line in a config file, which defaults to
~/.loki/storage/storage-server.conf (or `storage-server.conf` inside the
--data-dir, if overridden).  A completely custom location can also be
specified using `--config-file /path/to/config`.
This effectively matches how lokid works for argument parsing: items
specified on the command-line override options in the config file.
=> Allow specifying arguments via config file

httpserver/CMakeLists.txt
This allows `make install` to work to install the httpserver binary from
a cmake build dir (and won't affect anything if you don't do such a
`make install`).
=> Add a cmake install target

common/include/loki_common.h, httpserver/http_connection.cpp, httpserver/main.cpp, httpserver/service_node.cpp, httpserver/service_node.h, httpserver/swarm.cpp, httpserver/swarm.h
- nodes are active (i.e. they do work) only while they are in the latest swarm list
- only print messages about changes in swarms when we are active
- a bit of refactoring in how swarm updates are applied (still passes integration tests)
=> Deactivate nodes when they get decommissioned; plus some refactoring

CMakeLists.txt, httpserver/CMakeLists.txt, httpserver/command_line.cpp, httpserver/command_line.h, httpserver/main.cpp, unit_test/CMakeLists.txt, unit_test/command_line.cpp
- Moved the git hash/timestamp execution form top-level CmakeLists to httpserver CmakeLists to prevent full recompile when running `make`
- Build static lib with httpserver logic and link it against main and unit test
- Moved logic (`get_home_dir`) out of `command_line_parser` (keep it dumb)
- Add unit tests for command line parser
=> Unit test for command line parser

common/include/loki_common.h, httpserver/http_connection.cpp, httpserver/http_connection.h, httpserver/service_node.cpp, httpserver/service_node.h, httpserver/swarm.cpp, httpserver/swarm.h
Diff smaller than it looks, had to move parse_swarm_update higher but didn't touch it
We are waiting for lokid to be finished syncing, then we (only once) make 3 requests to the 3 seed nodes and replace any default ips we have with valid ips from these nodes
Since lokid now stores the ips in the database this is more useful for new nodes, but our current check for if we have finished syncing is bugged so we can use the bootstrap nodes to improve this in a future PR
Haven't been able to test this as thoroughly as I would have liked since lokid now stores IPs in the database so might try and write some tests
=> Bootstrap ips

httpserver/http_connection.cpp, httpserver/http_connection.h, httpserver/https_client.cpp, httpserver/service_node.cpp, httpserver/service_node.h
Under certain circumstances client connections would still be kept around waiting for notifications even if their corresponding sockets were closed. This PR fixes that. (Eventually they would be cleaned up though, in particular whenever a node would receive a batch of messages.)
Also, some log messages have been improved.
=> Don't foget to unsubscribe connections from message notifications

httpserver/service_node.cpp, httpserver/service_node.h, httpserver/swarm.cpp, httpserver/swarm.h
We no longer need to get the target height from lokid
=> Bootstrap on startup and use the target height from bootstrap nodes to determine when we have finished syncing

README.md
The version of libsodium on Ubuntu 16 (1.0.8) is not compatible. I verified it works with 1.0.16.   It's possible it works with an even older version.
=> Provide a min version for sodium

httpserver/http_connection.cpp, httpserver/service_node.cpp, httpserver/service_node.h
- show the reason the storage server is not active yet (e.g. "not on hardfork 12 yet")
- don't use target height if we can't contact any seed node (and assume we are synced)
=> Show the reason for not activating the storage server

httpserver/CMakeLists.txt, httpserver/http_connection.cpp, httpserver/https_client.cpp, httpserver/net_stats.h, httpserver/service_node.cpp
- return the number of open connections of each type (assuming connections are closed by the time the constructor is called)
- return the number of currently stored messages
=> Add the number of active connections of each type in get_stats

common/CMakeLists.txt, common/include/dev_sink.h, common/include/loki_logger.h, common/src/loki_logger.cpp, httpserver/http_connection.cpp, httpserver/http_connection.h, httpserver/https_client.cpp, httpserver/main.cpp, httpserver/security.cpp, httpserver/security.h, httpserver/serialization.cpp, httpserver/service_node.cpp, httpserver/stats.h, httpserver/version.h, storage/src/Database.cpp
- reduce severity of most log messages from `error` to `debug` (most of them having to do with other nodes, not the current node)
- add `get_logs` endpoint to provide most recent error log entires (limited to 1 request per second)
=> Clean up log messages

httpserver/http_connection.cpp, httpserver/service_node.cpp, httpserver/stats.cpp, httpserver/stats.h
Provides stats for the latest 1-hour period in addition to the existing "total since restart".
=> Add the number of recent store/retrieve requests to stats

httpserver/CMakeLists.txt, httpserver/dns_text_records.cpp, httpserver/dns_text_records.h, httpserver/service_node.cpp, httpserver/service_node.h
- periodically query `storage.version.loki.network` dns record for the latest version
- print a warning if our version is behind
=> Warn the operator if the version of the storage server is out of date

httpserver/http_connection.cpp
- fixed not decrementing lokid connection count when a request times out, resulting in incorrectly reporting a large number of open http connections in `get_stats`.
=> Fix incorrectly decrementing open http connections on timeout

common/include/loki_common.h, httpserver/CMakeLists.txt, httpserver/dns_text_records.cpp, httpserver/http_connection.cpp, httpserver/http_connection.h, httpserver/https_client.cpp, httpserver/reachability_testing.cpp, httpserver/reachability_testing.h, httpserver/service_node.cpp, httpserver/service_node.h, httpserver/swarm.cpp, httpserver/swarm.h, utils/include/utils.hpp, utils/src/utils.cpp
- Keep track of all nodes that failed the reachability test.
- Periodically test two nodes: one randomly selected and one that is known to have failed previously (this is done to give failing nodes a better chance to be recommissioned as soon as possible once they are back online).
- When a node is not reachable for longer than 120mins (to match uptime proofs) it will be reported to Lokid via a new endpoint. The same endpoint is used to report previously offending nodes as healthy.
- To be on the safe side and keep things simple, there is currently some redundancy in how many times a node's status is reported to Lokid.
=> Bookkeeping for reachability of nodes; reporting them to Lokid

httpserver/http_connection.cpp, httpserver/http_connection.h, httpserver/service_node.cpp, httpserver/service_node.h
- Derive tester/testee based on the firth most recent block (instead of the most recent block) to minimise discrepancies between nodes due to alternative chains. This is not meant to be bulletproof, just an improvement over what we have now; we could have used checkpoints, but they come with they come with their own problems).
- Add `height` parameter to blockchain test requests, so we can check tester/testee in the future (turns out it wasn't already there for blockchain testing, but was/is for storage testing).
- Use pubkey instead of snode address to avoid extra memory allocations.
=> Derive tester/testee based on older (more stable) block

httpserver/http_connection.cpp, httpserver/service_node.cpp, httpserver/service_node.h, httpserver/stats.h
- send different response if storage test parameters seem wrong (e.g. wrong tester)
- record whether storage test was rejected rather than simply failed
=> Record whether storage test was rejected by testee

httpserver/reachability_testing.cpp, httpserver/reachability_testing.h
expire() wasn't returning a value causing a crash when called.
=> Fix a crash when expiring

httpserver/http_connection.cpp, httpserver/service_node.cpp
- Responds to reachability tests even if the node is inactive (syncing, decommissioned, or not in any swarm). This is mostly done for decommissioned nodes as we wouldn't be able to test them otherwise.
- Increased interval to 10s for reachability tests.
=> Fix inactive nodes not responding to reachability tests

httpserver/command_line.cpp, httpserver/command_line.h
Currently if you specify `--testnet` but leave the default lokid rpc port
you still get 22023 which was unexpected; this updates the default to
lokid's default 38157 if `--testnet` is given but the lokid rpc port is
not explicitly specified.
=> Use default testnet rpc port under --testnet

httpserver/swarm.cpp
To be able to test decommissioned nodes, we need to be able to find them by their pubkey. This PR fixes not using the full list of nodes (i.e. not including decomm. nodes) on lookup.
=> Fix not being able to find decommissioned node

httpserver/service_node.cpp
It doesn't make sense to call `get_n_service_nodes` while the previous call of the same type is still being executed. Here we start the timer only after we are done with the previous call (whether it was successful or not).
=> Fix making unnecessary swarm requests to lokid in some exceptional cases

httpserver/http_connection.cpp, httpserver/http_connection.h, httpserver/https_client.cpp, httpserver/https_client.h, httpserver/main.cpp, httpserver/net_stats.h, httpserver/service_node.cpp, utils/include/utils.hpp, utils/src/utils.cpp
- deadline timer shutdowns the socket properly (as a bonus this results in fewer errors being printed);
- some accounting of open sockets (exposed via `get_stats`);
=> Http client code improvements and open file descriptor diagnostics

httpserver/service_node.cpp, httpserver/service_node.h
We want to minimise the number of connections to other SS, so instead of relaying messages individually, we accumulate them in a buffer, processing it periodically (every 200ms).
=> Always relay messages in batches

httpserver/http_connection.cpp, httpserver/https_client.cpp
If we fail to accept a new connection we are unlikely to be able to succeed immediately after, so we introduce a short delay.
=> Delay accepting new connections if failed

httpserver/http_connection.cpp, httpserver/http_connection.h, httpserver/https_client.cpp
- makes sure we remove all listeners whenever we cancel the deadline timer
=> More robust clean-up for incoming connections

common/include/loki_logger.h, crypto/include/lokid_key.h, crypto/src/lokid_key.cpp, httpserver/command_line.cpp, httpserver/command_line.h, httpserver/http_connection.cpp, httpserver/http_connection.h, httpserver/main.cpp, utils/include/utils.hpp, utils/src/utils.cpp
This changes storage server to fetch the SN private key via the RPC call added in lokid 6.x (which is also used by lokinet) at startup (i.e. before starting the main event loop), and allows the local RPC ip to be specified on the command-line.
As a useful side effect of this change it delays storage server startup until lokid is ready and running as a service node, which means we get earlier diagnostics about failures from storage server.  It also means that lokid is very likely to get a ping from the storage server right away--currently if you restart both storage server starts up must faster and so the first ping typically fails, which means lokid can't send uptime proofs until after the second ping.
The `--lokid-key` option is still accepted as an argument but now ignored (so that …
=> Lokid 6.x key fetching & local RPC ip override

httpserver/http_connection.cpp, httpserver/http_connection.h, httpserver/https_client.cpp, httpserver/https_client.h, httpserver/service_node.cpp, httpserver/service_node.h, httpserver/swarm.cpp, httpserver/swarm.h
Added a `/proxy` http target that expects:
1. "X-Target-Snode-Key" header: ed25519 public key of the target snode (the one we ultimately want to reach) in hex.
2. "X-Sender-Public-Key" header: x25519 ephemeral public key generated by the messenger client in hex.
3. Regular messenger http request (body + headers) serialised as json and encrypted with ECDH using "X-Sender-Public-Key" and the snode's x25519 public key.
"First hop" snode will find the target snode and forward the body along with "X-Sender-Public-Key" to that snode. Target snode will decrypt the request and process it normally with the only difference that that it will encrypt the entire response with ECDH for the original client and put the entire response as the body in response to "first hop" snode. "First hop" snode in …
=> Allow messenger clients to proxy to other snodes

httpserver/http_connection.cpp, httpserver/http_connection.h, httpserver/https_client.cpp, httpserver/https_client.h, httpserver/service_node.cpp
- allow to proxy to `https://file.lokinet.org` exclusively;
- unlike proxy to snodes, there is no encryption other than tls;
=> Allow messenger clients to proxy to Loki's file server

httpserver/rate_limiter.cpp, httpserver/rate_limiter.h, httpserver/version.h
This will be necessary SNs will be used for messenger proxy requests.
=> Allow more frequent requests between SN. Bump version to 1.0.9.

httpserver/http_connection.cpp
Fixes validation failure errors when getting privkeys from Loki.  (The ed25519 keys are 64 bytes versus 32 bytes for the other two.)
=> Fix length validation for ed25519 key

httpserver/command_line.cpp
Binding to specific interfaces might not work with lokinet. Added `--bind-ip` to overwrite the default value.
=> Bind to 0.0.0.0 by default

httpserver/service_node.cpp, utils/include/utils.hpp, utils/src/utils.cpp
- Expose the thread-local static RNG in `utils`
- Make the thread-local static RNG actually seed itself from `std::random_device` rather than using the default fixed seed.
- Don't create and seed a new RNG from the system clock when a new random number is needed: the seeding is quite slow and it's much better for both performance and randomness to just draw from an existing `std::mt19937_64` object.  (Regarding randomness: MT19937 has a much larger state, 2^19937, than the 2^64 states of possible 64-bit seed values).
- Eliminates a FIXME about the slow performance caused by the above.
=> RNG optimizations

httpserver/service_node.cpp, httpserver/swarm.h
This lets lokid respond with a "unchanged" result when the block hasn't change which saves a lot of effort & data: currently storage server pumps around 400kB/s of data from lokid rpc.  The poll_block_hash (added in lokid 6) lets lokid just not generate or send the redundant data in the first place (it includes `"unchanged":true` to indicate that the block hash hasn't changed and completely omits the service node states).
=> Use get_n_service_node's poll_block_hash for swam updates

httpserver/http_connection.cpp, httpserver/service_node.cpp
Returning early without explicitly calling the completion handler would result in the session being alive until it times out. This fixes that.
=> Fix not responding immediately on proxy request

httpserver/http_connection.cpp
Some background messages (contact sync etc.) can exceed the max size of regular messages.
=> Increase message size limit to 100KB

httpserver/service_node.cpp
- would fail to parse json from seed nodes otherwise
=> Fix incorrect requests to seed nodes

httpserver/CMakeLists.txt, httpserver/main.cpp, httpserver/service_node.cpp, httpserver/service_node.h
This allows running storage server as a Type=notify service, with systemd watchdog pings and a service status line.
Aside from allowing systemd watchdog to restart it, this gives a Status line (in `systemctl status loki-storage-server`) such as:
Status: "v1.0.9; sw=1743…1(n=5); 1325 msgs; reqs(S/R): 0/7; conns(in/http/https): 1/0/1"
=> Add systemd notify support

common/include/dev_sink.h
Upstream spdlog moves the instance and the absolute namespace qualifier
here breaks the code; this fixes it by going through the base class
which will work for both the bundled and newer spdlog versions.
Also changes the `fmt::memory_buffer` to `spdlog::memory_buf_t` because
the former doesn't work with newer libfmt's (which upstream spdlog and
the devendored debian sid build now use).
=> Fix spdlog compatibility

httpserver/service_node.cpp
All your favorite hits, such as:
- "Ugh, that foundation port is wrong. It's using the testnet node for both mainnet and testnet"
- "imaginary.stream:38157 is a mainnet node for confusing historic reasons, but changing it is good."
=> Fix foundation's mainnet port to not use testnet port

.gitmodules, CMakeLists.txt, httpserver/CMakeLists.txt, httpserver/lmq_server.cpp, httpserver/service_node.cpp
Use the exported cmake target (which gives both link libraries and any required include directories when used via `target_link_libraries`), and fix the includes to be the intended `lokimq/lokimq.h` instead of just `lokimq.h` so that potential future lokimq code that uses the full path include won't break storage server.
Also updates loki-mq to the latest (which is the same code, but with a bunch of build fixes and with the code rearranged/cleaned up to compile in multiple units, plus gained a version 1.0.0 and version header).
=> loki-mq updates

httpserver/http_connection.cpp
`this` is sometimes no longer valid when the callback runs, so use a weak pointer and check it instead.
I'm not 100% sure that a weak pointer (in the first two cases changed here) is correct:
- The weak_ptr instead assumes that the `connection_t` ownership responsibility is elsewhere, and that if the `connection_t` has been destroyed then that probably means a client closed the connection before getting the proxy response and thus the `weak_ptr` which just drops the response if the connection has gone away.
- As an alternative it could also use `self = shared_from_this()` in the lambda captures.  That would, however, keep the connection alive while the proxy request is being done.
=> Fix segfault when connection_t object is gone

httpserver/http_connection.cpp, httpserver/service_node.cpp, httpserver/swarm.cpp, httpserver/swarm.h
Without the full snode list inactive nodes will drop any lmq request from healthy nodes resulting in a timeout-long delay in onion requests.
=> Inactive nodes maintain the full snode list

httpserver/lmq_server.cpp, httpserver/reachability_testing.cpp, httpserver/reachability_testing.h, httpserver/service_node.cpp, httpserver/service_node.h
- check that both http and zmq ports need to be open
- if the node fails for 2 hours straight, report to lokid
=> Reachability testing via lokimq ports

httpserver/service_node.cpp
- `connect_remote` has no timeout by default
=> Disconnect after connect_remote

httpserver/lmq_server.cpp
- Updates lokimq to 1.0.3 to fix segfault when initiating requests.  This was triggered when initiating a request to a remote SN that *was* previously connected to us but isn't any longer: when we try to send, the send fails, then we try again with a new outgoing connection.  This "try again" step was recursing and trying to take over pointer ownership that the previous step had already taken over.
- Includes some other minor code improvements (matching up lmq logging, replacing std::bind, and using nicer LMQ command initialization) that I made when investigating.  They aren't required for the fix, but are nice to have.
=> lokimq segfault fix

httpserver/http_connection.cpp, httpserver/lmq_server.cpp, httpserver/main.cpp, httpserver/request_handler.cpp, httpserver/request_handler.h
- Add `get_lns_mapping` endpoint for Session, which takes one parameter `name_hash` and makes an LNS request to Lokid on behalf of the client.
- Fix onion requests potentially resulting in a crash due to request timeout.
- Remove some unused HTTP code for SN-SN communication.
=> Allow LNS requests for Session clients

httpserver/lmq_server.cpp, httpserver/service_node.cpp
- try to reuse the same outgoing connection for peer testing, so we don't have to manually close it
=> Peer testing fix

common/src/loki_logger.cpp, httpserver/http_connection.cpp, httpserver/lmq_server.cpp, httpserver/reachability_testing.cpp, httpserver/request_handler.cpp, httpserver/service_node.cpp, httpserver/swarm.cpp
- only bootstrap from seed after first having contacted local lokid (we can't apply ip changes when the node list is empty)
- forward more errors in proxy requests to the client
=> Improve error handling in proxy requests

httpserver/lmq_server.h
Updates to 1.0.5 with a fix that can cause message reception delays of up to 250ms.  (Though I believe only under certain connect/disconnect patterns).
1.0.5 also broke SS's forward declaration of `string_view` (because it grew the capability of handling char types other than `char`); the underlying simple_string_view class is an implementation detail that isn't meant to be used (and may not exist at all: lokimq uses std::string_view instead if the compiler provides it).
=> Update to lmq 1.0.5 & fix compilation

httpserver/request_handler.cpp, httpserver/service_node.cpp
All these requests use lmq after the `LOKIMQ_ONION_HARDFORK` hardfork, so the corresponding http code is no longer needed
=> Remove stale http code

httpserver/lmq_server.cpp, httpserver/lmq_server.h, httpserver/service_node.cpp, httpserver/service_node.h, httpserver/swarm.h
Assigning a connection's SN status at connection time is not working
well: it results in excess reconnections and test failures, since
currently the behaviour goes something like this:
- SS has many other SSes connected to it.
- SS restarts
- Other SSes see the closed connection and reconnect
- Many of these reconnections are fast enough that the SS doesn't have
the SS list loaded yet, and so they all get service node status set to
false.
- One of the SSes makes a request (either onion routing something, or
doing a reachability test).
- SS says "BYE" to tell the remote to disconnect.
- Remote disconnects, and the request fails.
- Remote tests again sometime later and reconnects, this time
gets noticed as a SN and allowed.
There's a related overhang issue where a connected SN keeps its SN …
=> LokiMQ SN authenication overhaul

common/include/loki_common.h, httpserver/http_connection.cpp, httpserver/lmq_server.cpp, httpserver/reachability_testing.cpp, httpserver/reachability_testing.h, httpserver/service_node.cpp, httpserver/service_node.h, httpserver/stats.h
- Displays a warning when the node hasn't been pinged (independently over zmq and http) by any other node for a long time (3 min currently).
- Decomissioned nodes no longer attempt to ping other nodes (they would fail anyway).
- Silence storage testing errors (since they are not enforced yet).
=> Notify operator when their node seems unreachable

common/CMakeLists.txt, httpserver/CMakeLists.txt, pow/CMakeLists.txt, storage/CMakeLists.txt, utils/CMakeLists.txt
Headers aren't supposed to be listed in `add_library` calls and are an
unfortunately common cmake anti-pattern.  (cmake does *not* need headers
listed to know how to check that things need rebuilding when a header
changes, which seems to be the reason people think they have to include
them).
Apparently this antipattern emerged partly because of buggy behaviour in
MSVC pre-2017 that didn't understand how to find headers when loading a
CMake project.
=> Remove headers from cmake add_library

httpserver/main.cpp, httpserver/version.h
Currently --version is sort of awkward: it doesn't print anything at all
if you run it with `--log-level warning` (or if you have that in a
config file), and it prints the version info *after* initializing (and
printing various info about) the logger, which makes the output kind of
messy.
This simplifies it to print the version (and exit) much earlier in the
startup when `--version` is given (and leaves the existing logged
version print as is).
(This also makes a minor tweak to the current `print_version` from
`static` to `inline` so that the linker can throw away the duplicates
rather than keeping duplicates for each compilation unit that includes
version.h.)
=> Make --version print without initializing logger

httpserver/CMakeLists.txt, httpserver/dns_text_records.cpp
- Updates lokimq to the latest master (which contains a few small fixes/tweaks, including a freebsd compilation fix).
- Only link to `-lresolv` if it exists (it doesn't on BSDs because the functions are part of libc).
- Fix a missing header needed for the resolv.h functions being used
Fixes #377
=> BSD compilation fixes

httpserver/CMakeLists.txt
This makes it not try installing the static lib + headers if doing a `make install`.
=> Remove lokimq from 'all'

httpserver/CMakeLists.txt, httpserver/http_connection.cpp, httpserver/https_client.cpp, httpserver/lmq_server.cpp, httpserver/lmq_server.h, httpserver/notifier.cpp, httpserver/notifier.h, httpserver/request_handler.cpp, httpserver/service_node.cpp, httpserver/service_node.h
- Add an lmq enpoint available to the notification server, which allows subscribing to messenger pubkeys.
- Change the default POW difficulty to 1.
- Fix an authorisation bug in the https client.
=> Add lmq endpoint for the notification server

common/include/loki_common.h, crypto/CMakeLists.txt, httpserver/CMakeLists.txt, httpserver/http_connection.cpp, httpserver/http_connection.h, httpserver/https_client.cpp, httpserver/lmq_server.cpp, httpserver/lmq_server.h, httpserver/onion_processing.cpp, httpserver/request_handler.cpp, httpserver/request_handler.h, httpserver/service_node.cpp, httpserver/service_node.h, utils/include/utils.hpp
Adds `onion_req/v2` endpoint, which expects payload to be encoded as `| <4 bytest Little-endian> N | <N bytes> ciphertext | <utf8 encoded json> |`
=> Add support for v2 onion requests

common/include/dev_sink.h, httpserver/command_line.cpp, httpserver/command_line.h, httpserver/http_connection.cpp, httpserver/http_connection.h, httpserver/lmq_server.cpp, httpserver/lmq_server.h, httpserver/main.cpp, httpserver/service_node.cpp, httpserver/service_node.h
- Added two LMQ endpoints that require authentication with a key (set via `stats_access_key` as hex string): `service.get_stats` and `service.get_logs`
- `gets_stats` http endpoint now only returns the version number (session clienst might need it)
=> Stats and logs require operator key

httpserver/http_connection.h
This causes a (fatal, with the default `-Werror`) warning under clang.
=> Fix mismatched struct/class forward declaration

httpserver/http_connection.cpp, httpserver/service_node.cpp
Boost 1.73 warns when including <boost/bind.hpp> (about dropping support for global namespace _1, _2, etc.).  SS doesn't use those anyway, so can just switch to the more specific header that doesn't give the deprecation warning.
=> boost 1.73+ compatibility without deprecation warning

utils/src/utils.cpp
Some "control" messages in Session require longer ttl.
=> Increase max ttl to 14 days

httpserver/command_line.cpp
Adds lokid-rpc-ip and lokid-rpc-port as hidden options so that they still work if specified on command line or in the config file.
=> Make `lokid-rpc-ip` and `lokid-rpc-port` options still work

httpserver/https_client.cpp, httpserver/https_client.h
Tls handshake may fail if SNI is set incorrectly (or unset), which was the case for @nielsandriesse's server.
=> Set SNI correctly in outgoing https requests

httpserver/service_node.cpp
Currently lokinet pings with a 30s interval, and oxend in the next
release will use a similar interval for internal checks for when it
should send uptime proofs; this unifies storage server to use the same
ping frequency.
=> Reduce oxend ping interval to match lokinet/oxend

httpserver/request_handler.cpp, httpserver/request_handler.h, storage/include/Database.hpp, storage/src/Database.cpp, unit_test/storage.cpp
~- Session will use this endpoint to keep its node list up to date (it will still call a seed node on the very first startup).~
~- Returns the following fields: `[public_ip, storage_port, storage_lmq_port, pubkey_ed25519, pubkey_x25519]` (Session isn't currently using the lmq port, but I put it in there just in case).~
~- It is only currently availabe via onion requests (method name is `get_all_service_nodes`).~
- Session clients can use `oxend_request` via onion requests and have their requests proxied to oxend.
- Only `get_service_nodes` and `ons_resolve` are currectly allowed
Request Example:
```json
{
"endpoint": "get_service_nodes",
"oxend_params": {
"limit": 1000,
"active_only": true
}
}
```
=> Add 'get_all_service_nodes' endpoint 

httpserver/request_handler.cpp
Fix `allowed_endpoints` filter by using `std::string` instead of `const char*`.
=> Fix allowed endpoints unordered_set to be strings

contrib/onion-request.cpp, httpserver/http_connection.cpp, httpserver/lmq_server.cpp, httpserver/onion_processing.cpp, httpserver/onion_processing.h, httpserver/oxend_rpc.cpp, httpserver/request_handler.cpp, httpserver/request_handler.h
Allows a client to opt-out of json double-encoding and base64 encoding of encrypted onion request data.
See commit descriptions for details.
TL;DR:
- add `"json":true, "base64":false` into the onion control section (where "headers" is) to get rid of base64 encoding + double json
- oxend requests embed json objects instead of json string, renames "oxend_params" to "params", and makes it optional.
=> JSON/base64 opt-out for onion requests + oxend rpc proxy unwrapping

CMakeLists.txt, contrib/onion-request.cpp, crypto/include/channel_encryption.hpp, crypto/src/channel_encryption.cpp, httpserver/http_connection.cpp, httpserver/lmq_server.cpp, httpserver/lmq_server.h, httpserver/main.cpp, httpserver/onion_processing.cpp, httpserver/onion_processing.h, httpserver/request_handler.cpp, httpserver/request_handler.h, httpserver/service_node.cpp, httpserver/service_node.h, unit_test/encrypt.cpp, unit_test/onion_requests.cpp
Redoes the SS-to-SS OMQ protocol to use a bencoded dict as data.
This allows passing other metadata parameters such as the hop number and encryption type, and allows future protocol extensions without needing a new endpoint.
Also adds a max hop length of 15, and allows the client to start somewhere other than 0 by adding `"hop_no": N` into the initial onion request.
Finally, this adds xchacha20-poly1305 encryption by passing `"enc_type": "xchacha20"` in the onion request metadata.  (Note that this uses a more secure shared key format of `H(aB || A || B)` rather than just `aB` so needs some client-side changes to start using).
This is all backwards compatible:
- up until HF18, sn.onion_req_v2 is still used (which is always gcm, and doesn't have hop limits)
- clients making onion requests …
=> SS-to-SS onion req internal protocol refactor, max hops, xchacha20 encryption
