oxen-io/oxen-storage-server

httpserver/CMakeLists.txt
httpserver/http_connection.hpp
pow/CMakeLists.txt

Hashing the message contents appended together and storing the the database for uniquely identifying messages

Hashing the message and storing that in the database

---

httpserver/http_connection.hpp
pow/include/pow.hpp
pow/src/pow.cpp
storage/include/Item.hpp
storage/include/Storage.hpp
storage/src/DatabaseHandler.cpp
storage/src/DatabaseHandler.hpp
storage/src/Storage.cpp

Refactored the way the server was building it's json to use a boost ptree library
Now storing and handling the message contents as string instead of vector
Now the ttl is a uint64_t in the storage logic, Sasha will be merging more ttl changes

Write json

---

httpserver/http_connection.hpp
pow/CMakeLists.txt
pow/include/utils.hpp
pow/src/pow.cpp

This will also be useful to the http server code that needs to parse the ttl

add parseTTL util function

---

.gitignore
httpserver/http_connection.hpp

Also tracking vscode workspace settings and tasks

Sending the last hash with a message request

---

httpserver/http_connection.hpp
pow/include/utils.hpp

Parsing the ttl to an integer first so check validity before we calculate the PoW hash, ttl now has a max of 4 days

Max ttl limit

---

README.md
unit_test/CMakeLists.txt
unit_test/main.cpp
unit_test/pow.cpp
unit_test/storage.cpp

Add unit tests for Pow and Storage using Boost' unit testing framework.

Add unit tests for pow and storage apis

---

httpserver/http_connection.hpp

Implements #13 
Note that I'm probably going to refactor things to move as much logic out of the httpserver and into the library, so function signatures are quite temporary at this stage.

Json rpc api

---

crypto/src/test_main.cpp

Fix missing include

---

httpserver/http_connection.cpp
httpserver/serialization.cpp
httpserver/serialization.h
httpserver/service_node.cpp
httpserver/service_node.h
storage/include/Item.hpp
unit_test/storage.cpp

- unify member names in Item and message_t
- use template functions for serializing
- serialize saved messages and send them to peers in batches

bootstrapping swarm peers with messages in batches

---

httpserver/common.h
httpserver/service_node.cpp
httpserver/swarm.cpp

Fix << operator for sn_record_t and remove to_string()

---

httpserver/http_connection.cpp
storage/CMakeLists.txt
storage/src/Database.cpp
utils/include/utils.hpp
utils/src/utils.cpp

Check that the timestamp the client sends is not in the future or already expired
Moved get_time_ms to utils
Also snuck in formatting utils functions copied from lokid to use 4 spaces

Timestamp validity check

---

unit_test/CMakeLists.txt
unit_test/pow.cpp
unit_test/storage.cpp

Changed the Pow unit test to use data generated with the release value NONCE_TRIALS = 1000 (Thanks @BeaudanBrown ! Good stuff) that way the unit tests can be built and run in both debug and release.

Fix unit tests

---

unit_test/pow.cpp

Fix pow data used in unit_tests not being valid

---

httpserver/http_connection.cpp
httpserver/http_connection.h

Also improved encapsulation in HttpClientSession

add deadline timer to outgoing http sessions

---

httpserver/serialization.cpp

Xcode hinted me on those two :)

Remove unused variables in serialization.cpp

---

unit_test/CMakeLists.txt
unit_test/serialization.cpp

Simple unit test for serialization:
- serialize then unserialize then check if the data is still the same.
- check that batches are created.

Add unit tests for serialization

---

storage/src/Database.cpp

Kudos to @msgmaxim's good eye!

Add ORDER BY in sql SELECT statement to prevent undefined order

---

.travis.yml
Makefile
crypto/CMakeLists.txt
install-deps-linux.sh
unit_test/pow.cpp
unit_test/storage.cpp

~~This PR is mostly a way for feedback to develop the config file.
Please ignore until specified otherwise!~~
Should be good to go!

Hook up to travis CI

---

crypto/include/channel_encryption.hpp
crypto/src/channel_encryption.cpp
crypto/src/test_main.cpp
httpserver/main.cpp

Parse the private key and generate the public key in main instead of channelEncryption
Set default key location

Move key parsing

---

httpserver/http_connection.cpp
httpserver/service_node.cpp

Prepare request payload for swarm update to have proper content-length. Double check for null swarm

Prepare swarm update request

---

crypto/src/channel_encryption.cpp
httpserver/http_connection.cpp
httpserver/http_connection.h
httpserver/service_node.cpp
httpserver/service_node.h
httpserver/swarm.cpp
httpserver/swarm.h

plus some other, minor improvements

Enforce message size limit on the server side

---

httpserver/common.h
httpserver/http_connection.cpp
httpserver/http_connection.h
httpserver/main.cpp
httpserver/service_node.cpp
httpserver/service_node.h

This PR just gets some aesthetic changes out of the next PR on signatures.
Some changes are from running `make format`, no idea why it's coming up only now...

Improve naming and pass-by-reference consistency

---

crypto/src/lokid_key.cpp
httpserver/main.cpp

Better error handling on startup

---

httpserver/common.h
httpserver/http_connection.cpp
httpserver/http_connection.h
httpserver/service_node.cpp
httpserver/service_node.h
httpserver/swarm.h
utils/include/utils.hpp
utils/src/utils.cpp

- keeping track of blockchain height and the latest hash
- select tester and testee on every block

Peer testing, part I: select tester and testee

---

storage/include/Database.hpp
storage/include/Item.hpp
storage/src/Database.cpp

- plus better error handling in db code

Add db methods necessary for retrieving a random row

---

httpserver/common.h
httpserver/http_connection.cpp
httpserver/http_connection.h
httpserver/service_node.cpp
httpserver/service_node.h
storage/include/Database.hpp
storage/src/Database.cpp
utils/include/utils.hpp
utils/src/utils.cpp

- find block hash for the requested height (retry later if behind)
- check if we are the testee
- check messages (retry later if not found)
- respond to a test

Peer testing, part II (final)

---

crypto/CMakeLists.txt
crypto/src/signature.cpp
vendors/loki/crypto-ops/hash-ops.c
vendors/loki/crypto-ops/hash-ops.h
vendors/loki/crypto-ops/int-util.h
vendors/loki/crypto-ops/keccak.c
vendors/loki/crypto-ops/keccak.h

- changed to match signing in lokid

use keccak1600 in signatures

---

.vscode/c_cpp_properties.json
crypto/include/lokid_key.h
crypto/include/signature.h
httpserver/CMakeLists.txt
httpserver/http_connection.cpp
httpserver/main.cpp
httpserver/rate_limiter.cpp
httpserver/service_node.cpp
httpserver/service_node.h
pow/include/pow.hpp
pow/src/pow.cpp
unit_test/pow.cpp

Redoing this PR onto dev instead of master, ignore (I'm dum(

Pow difficulty (Again)

---

httpserver/service_node.cpp
httpserver/service_node.h

Ping lokid regularly

---

httpserver/main.cpp
httpserver/service_node.cpp
httpserver/service_node.h

Edit: I wanted to use that branch name for something else :(

Create a new thread for querying the pow dns entry

---

httpserver/service_node.cpp

Not 100% how this was working before but it definitely isn't now

Need more bitzz

---

httpserver/service_node.cpp

After last PR realised this could be cleaned up a bit
Move clearnet logic to make_sn_request function and make sure it is used everywhere

Use make_sn_request everywhere

---

httpserver/http_connection.cpp
httpserver/http_connection.h

Only retry storage test for 1 min. Plus a cheeky format

Stop retrying

---

httpserver/http_connection.cpp
httpserver/http_connection.h
httpserver/main.cpp
httpserver/server_certificates.h

- also use `~/.loki/storage` as the default database location
- use that location for ssl keys/certificate

better command line argument handling

---

httpserver/http_connection.cpp
httpserver/rate_limiter.cpp
httpserver/rate_limiter.h
unit_test/rate_limiter.cpp

Rate limit clients (hopefully) and a few tests

Client rate limiter plus tests

---

httpserver/http_connection.cpp
httpserver/main.cpp
httpserver/service_node.cpp
httpserver/service_node.h
httpserver/swarm.h

Use the get_n_service_nodes endpoint
Guard certain requests unless hardfork > 12 and we are in a swarm

Check hardfork

---

httpserver/main.cpp

Fix using the logger before it is initialized

---

httpserver/main.cpp

- IP and port can be specified anywhere (and are now extracted via boost
hidden positional options rather than trying to pull them out of argv).
- fixes a segfault for unknown options.  This was caused because boost
raises an exception on unknown options, but that was attempting to
invoke the log system which hasn't been set up yet.  The exception now
gets caught and printed so you get a nicer message like:
Invalid options: unrecognised option '--afaewf'
- added `--help` that just prints the help message.
- slightly reordered the options by moving `--version` next to the
bottom, with (new) `--help`, rather than in the middle of the business
options.

Various improvements to command-line arguments

---

httpserver/http_connection.h
httpserver/service_node.cpp

This was a bit silly since it wasn't doing anything async and will make the ip bootstrapping a bit easier

Make parse_swarm_update take a block update reference rather that a callback

---

httpserver/http_connection.cpp

Hopefully this might alleviate the handshake complains...

Shutdown stream instead of closing socket

---

httpserver/https_client.cpp

- using pub key instead of socket endpoint as it seems to cause a crash when we close it on deadline timer
- `start` just got moved to the top (unmodified)

Don't use a potentially closed socket

---

httpserver/http_connection.cpp

Deadline timers prolong the life of connections unless cancelled. This PR makes sure we cancel the timer when we don't need the connection anymore (a few failure cases).

Cancel the deadline timer as soon as possible for incoming connections

---

CMakeLists.txt

I think this should be the default behaviour

Default to snode sigs on

---

httpserver/service_node.cpp

The TXT parsing was expecting a null-terminated string, but that
apparently isn't what we get back here; instead we get back a series of
packed N...[N...] values where `N` is a byte indicating the length (up
to 255) of the ... data.
Also adds some debugging and warnings on lookup.

Fix PoW TXT parsing, add some failure debugging

---

.gitignore
httpserver/main.cpp

Ignore swapfiles and reject localhost binding

---

httpserver/service_node.cpp

As Lokid was changed to expect integers.

From strings to numbers for version triplet in ping json

---

common/include/loki_common.h
httpserver/http_connection.cpp
httpserver/http_connection.h
httpserver/service_node.cpp
httpserver/service_node.h
httpserver/swarm.cpp
httpserver/swarm.h
utils/include/utils.hpp
utils/src/utils.cpp

Ground work for "online status" testing. Pings other service nodes, but does not handle the result yet.

Periodically ping other service nodes

---

common/include/loki_common.h
crypto/include/lokid_key.h
crypto/src/lokid_key.cpp
crypto/src/signature.cpp
httpserver/command_line.cpp
httpserver/command_line.h
httpserver/http_connection.cpp
httpserver/http_connection.h
httpserver/main.cpp
httpserver/security.cpp
httpserver/service_node.cpp
httpserver/service_node.h
httpserver/swarm.cpp
httpserver/swarm.h
pow/src/pow.cpp
unit_test/command_line.cpp
unit_test/signature.cpp
utils/CMakeLists.txt
utils/include/utils.hpp
utils/src/utils.cpp

- Fix compilation with newer boost
- Receive x25519 key from Lokid and add a corresponding (hidden) command line option for testing, derive x25519 pubkey
- Some clean up

Incorporate new lokid keys and more

---

httpserver/service_node.cpp

Added `public.loki.foundation`

Update seed nodes

---

.gitmodules
CMakeLists.txt
common/include/loki_common.h
crypto/CMakeLists.txt
crypto/include/channel_encryption.hpp
crypto/include/lokid_key.h
crypto/src/channel_encryption.cpp
crypto/src/lokid_key.cpp
crypto/src/test_main.cpp
httpserver/CMakeLists.txt
httpserver/command_line.cpp
httpserver/command_line.h
httpserver/http_connection.cpp
httpserver/http_connection.h
httpserver/https_client.cpp
httpserver/lmq_server.cpp
httpserver/lmq_server.h
httpserver/main.cpp
httpserver/request_handler.cpp
httpserver/request_handler.h
httpserver/service_node.cpp
httpserver/service_node.h
httpserver/swarm.cpp
httpserver/swarm.h

- uses lokimq for SN-SN communications after HF15
- allows to send onion requests with some SS as destination

Initial lokimq integration. Onion requests to SS.

---

README.md

include --recursive in submodules and other minor notes

update readme for latest loki-mq

---

httpserver/reachability_testing.cpp

- warn every 2 mins instead of 10 seconds

Less frequent reachability warnings

---

httpserver/http_connection.h
httpserver/lmq_server.cpp
httpserver/service_node.cpp

large files may take a long time to pass around

Increase lokimq request timeout

---

httpserver/http_connection.cpp
httpserver/http_connection.h

Changing these break SS communications.

Revert X-Oxen-* header changes

---

httpserver/swarm.cpp
httpserver/swarm.h
unit_test/CMakeLists.txt
unit_test/service_node.cpp

- This was most likely causing #409

Fix not updating ip addresses of snodes
